import fromArr from "../functions/from.js";
import Dialogue from "../managers/Dialogue.js";

export function parse (str) {
  let lines = str.split("\n");
  let dialogues = [];

  for (let i = 0; i < lines.length; i++) {
    let line = lines[i];
    
    if (!line.startsWith("Dialogue: ")) {
      continue;
    }

    let [,,start,end,,,,,,,text] = line.match(/(\d),(\d{1,}:?\d{1,2}:\d{1,2}[,.]\d{1,3}),(\d{1,}:?\d{1,2}:\d{1,2}[,.]\d{1,3}),(\w+)?,(\w+)?,(\d+),(\d+),(\d+),(\w+)?,(.+)/);
    
    dialogues.push(
      new Dialogue({ start, end, text })
    );
  }

  return fromArr(dialogues);
}

export function convert (dialogues) {
  if (!Array.isArray(dialogues)) return null;
  
  let headerStr = `[Script Info]\n; Script generated by Aegisub 3.2.2\n; http://www.aegisub.org/\nTitle: Default Aegisub file\nScriptType: v4.00+\nWrapStyle: 0\nScaledBorderAndShadow: yes\nYCbCr Matrix: None\n[Aegisub Project Garbage]\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n`;

  return headerStr + dialogues.map(
    dialogue => `Dialogue: 0,${dialogue.end.toString(".")},${dialogue.end.toString(".")},Default,,0,0,0,,${dialogue.text}`
  ).join("\n");
}